/**
 * Rank de times — edite este array para alterar nomes, títulos e arquivo do escudo (pasta escudos/).
 * A ordem na tela é automática: mais títulos primeiro; em empate, ordem alfabética do nome.
 */
const TEAMS = [
  { name: "Corinthians", titles: 27, shield: "corinthians.png" },
  { name: "Atlético Mineiro", titles: 6, shield: "atletico-mg.png" },
  { name: "Vasco", titles: 5, shield: "vasco.png" },
  { name: "Grêmio", titles: 112, shield: "gremio.png" },
  { name: "Palmeiras", titles: 6, shield: "palmeiras.png" },
  { name: "Flamengo", titles: 11, shield: "flamengo.png" },
  { name: "Santos", titles: 2, shield: "santos.png" },
  { name: "Remo", titles: 5, shield: "remo.png" },
  { name: "Bahia", titles: 0, shield: "bahia.png" },
  { name: "Internacional", titles: 2, shield: "internacional.png" },
  { name: "Real Madrid", titles: 1, shield: "real-madrid.png" },
  { name: "Botafogo", titles: 4, shield: "botafogo.png" },
  { name: "Mirassol", titles: 2, shield: "mirassol.png" },
  { name: "Atlético Paranaense", titles: 0, shield: "athletico-pr.png" },
  { name: "Cruzeiro", titles: 5, shield: "cruzeiro.png" },
  { name: "Fluminense", titles: 0, shield: "fluminense.png" },
  { name: "Coritiba", titles: 4, shield: "coritiba.png" },
  { name: "Chapecoense", titles: 0, shield: "chapecoense.png" },
  { name: "Sao Paulo", titles: 4, shield: "sao-paulo.png" },
  { name: "Portuguesa", titles: 1, shield: "portuguesa.png" },
  { name: "Avai", titles: 1, shield: "avai.png" },
  { name: "Ceara", titles: 4, shield: "ceara.png" },
  { name: "Treze", titles: 1, shield: "treze.png" },
  { name: "Cascavel", titles: 1, shield: "cascavel.png" },
  { name: "Caxias", titles: 1, shield: "caxias.png" },
  { name: "Barcelona", titles: 1, shield: "barcelona.png" },
  { name: "Figueirense", titles: 3, shield: "figueirense.png" },
  { name: "Criciuma", titles: 3, shield: "criciuma.png" },
  { name: "Goianesia", titles: 1, shield: "goianesia.png" },
  { name: "Mazembe", titles: 1, shield: "mazembe.png" },
  { name: "Boca Juniors", titles: 1, shield: "boca-juniors.png" },
  { name: "Joinville", titles: 1, shield: "joinville.png" },
  { name: "Vitoria", titles: 1, shield: "vitoria.png" },
  { name: "fortaleza", titles: 2, shield: "fortaleza.png" },
  { name: "Atletico Goia", titles: 2, shield: "athletico-pr.png" },
  { name: "Trem", titles: 2, shield: "trem.png" },
  { name: "Uberlandia", titles: 1, shield: "uberlandia.png" },
  { name: "Bragantino", titles: 1, shield: "bragantino.png" },
   { name: "Arsenal", titles: 1, shield: "arsenal.png" },
  { name: "Gama", titles: 1, shield: "gama.png" },
  { name: "Porto Velho", titles: 1, shield: "porto-velho.png" },
  { name: "Botafogo da Paraiba", titles: 2, shield: "botafogo-pb.png" },
  { name: "Operario ms", titles: 1, shield: "operario-ms.png" },
  { name: "Figueirense", titles: 1, shield: "figueirense.png" },
  { name: "Confianca", titles: 2, shield: "confianca.png" },
  { name: "Santa Cruz", titles: 1, shield: "santa-cruz.png" },
  { name: "Vila nova", titles: 1, shield: "vila-nova.png" },
  { name: "Sport Recife", titles: 1, shield: "sport-recife.png" }
];
